VacationsSystem/Models/Leave.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using JetBrains.Annotations;
using Microsoft.Ajax.Utilities;
using VacationsSystem.ViewModels;

namespace VacationsSystem.Models
{
    public sealed class Leave
    {
        public enum LeaveTypeEnum
        {
            None = 0,
            Vacation = 1 << 0,
            Sick = 1 << 1,
            Abscence = 1 << 2,
            Maternal = 1 << 3,
            Other = 1 << 4
        }

        private static readonly Dictionary<LeaveTypeEnum, string> TypeNames = new Dictionary<LeaveTypeEnum, string>
        {
                { LeaveTypeEnum.Maternal, Resources.ExcelTypeNames.Maternal },
                { LeaveTypeEnum.Abscence, Resources.ExcelTypeNames.Abscence },
                { LeaveTypeEnum.Vacation, Resources.ExcelTypeNames.Vacation }
        };
        
        public enum LeaveStateEnum
        {
            None = 0,
            Created = 1 << 0,
            Submitted = 1 << 1,
            Approved = 1 << 2,
            Rejected = 1 << 3,
            [Display(Name = "Notified")]
            ApprovedAndNotified = 1 << 4,
            All = Created | Submitted | Approved | Rejected | ApprovedAndNotified
        }

        #region Contructors

        public Leave()
        { }

        public Leave(AddLeaveViewModel model, string creatorId)
        {
            this.Id = Guid.NewGuid().ToString();
            this.CreatorId = creatorId;
            this.LeaveTypeId = model.LeaveTypeId;
            this.StartDate = model.StartDate;
            this.EndDate = model.EndDate;
            this.Description = model.Description;
            this.LeaveStateId = (int) LeaveStateEnum.Created;
            this.DaysTaken = model.DaysTaken;
            this.UserId = !model.UserId.IsNullOrWhiteSpace() ? model.UserId : creatorId;
        }

        #endregion

        #region Properties

        [Key]
        public string Id { get; set; }

        [CanBeNull]
        [ForeignKey("User")]
        [Display(Name = "User")]
        public string UserId { get; set; }

        [CanBeNull]
        public User User { get; set; }
        
        [ForeignKey("LeaveType")]
        [Display(Name = "Leave type")]
        public int? LeaveTypeId { get; set; }
        
        [CanBeNull]
        [Display(Name = "Type")]
        public LeaveType LeaveType { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "Start date")]
        public DateTime? StartDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "End date")]
        public DateTime? EndDate { get; set; }

        [StringLength(1000)]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required]
        [ForeignKey("LeaveState")]
        [Display(Name = "Leave state")]
        public int? LeaveStateId { get; set; }

        [Display(Name = "State")]
        public LeaveState LeaveState { get; set; }

        [Display(Name = "Days taken")]
        public int? DaysTaken { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreationDate { get; set; }

        [CanBeNull]
        [ForeignKey("User")]
        [Display(Name = "Creator")]
        public string CreatorId { get; set; }

        [CanBeNull]
        public User Creator { get; set; }

        #endregion

        #region Public Methods

        public void UpdateLeave(AddLeaveViewModel model)
        {
            this.StartDate = model.StartDate;
            this.EndDate = model.EndDate;
            this.Description = model.Description;
            this.LeaveTypeId = model.LeaveTypeId;
            this.DaysTaken = model.DaysTaken;
        }

        public string GetTypeName()
        {
            return TypeNames[LeaveType];
        }

        #endregion
    }
}

VacationsSystem/Models/LeaveType.cs
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using VacationsSystem.Extensions;

namespace VacationsSystem.Models
{
    public class LeaveType
    {
        private LeaveType(Leave.LeaveTypeEnum @enum)
        {
            this.LeaveTypeId = (int) @enum;
            this.Name = @enum.ToString();
            this.Description = @enum.GetEnumDescription();
            this.Leaves = new ObservableCollection<Leave>();
        }

        protected LeaveType()
        {
            this.Leaves = new ObservableCollection<Leave>();
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int LeaveTypeId { get; set; }

        [Required, MaxLength(100)]
        public string Name { get; set; }

        [MaxLength(150)]
        public string Description { get; set; }

        [NotMapped]
        public ObservableCollection<Leave> Leaves { get; set; }

        public static implicit operator LeaveType(Leave.LeaveTypeEnum @enum) => new LeaveType(@enum);

        public static implicit operator Leave.LeaveTypeEnum(LeaveType type) => (Leave.LeaveTypeEnum) type.LeaveTypeId;
    }
}

VacationsSystem/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Nager.Date;
using VacationsSystem.Attributes;
using VacationsSystem.DAL.UnitOfWork;
using VacationsSystem.Extensions;
using VacationsSystem.Models;
using VacationsSystem.Services;
using VacationsSystem.ViewModels;

namespace VacationsSystem.Controllers
{
    [AuthorizeRedirect(Roles = "User")]
    public class LeaveController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly LeaveService leaveService;
        private readonly UserService userService;

        public LeaveController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
            this.userService = new UserService(unitOfWork);
            this.leaveService = new LeaveService(unitOfWork);
        }

        private static IEnumerable<string> GetCurrentHolidays(DateTime? start = null, DateTime? end = null)
        {
            return DateSystem.GetPublicHoliday(CountryCode.PL, start ?? DateTime.Now.AddMonths(-1), end ?? DateTime.Now.AddYears(1)).Select(h => h.Date.ToString("yyyy-MM-dd"));
        }

        #region HttpGet

        public async Task<ActionResult> Index(Leave.LeaveStateEnum? state)
        {
            state = state ?? Leave.LeaveStateEnum.All;
            var userId = this.User.Identity.GetUserId();
            var leaves = await this.unitOfWork.LeaveRepository.Find(
                l => (state.Value & (Leave.LeaveStateEnum) l.LeaveStateId) != 0 && l.UserId == userId,
                order: l => l.StartDate, includes: l => l.LeaveType);
            this.ViewBag.State = state;
            return this.View(leaves);
        }

        [AuthorizeRedirect(Roles = "Approver,Manager")]
        public async Task<ActionResult> OtherIndex(Leave.LeaveStateEnum? state, string sortOrder, ListSortDirection? orderDirection,
            string filterUser, [DataType(DataType.Date)] DateTime? filterStartDate, DateTime? filterEndDate, int? page)
        {
            filterStartDate = filterStartDate ?? DateTime.Now.Date.AddMonths(-1);
            filterEndDate = filterEndDate ?? DateTime.Now.Date.AddYears(1);
            state = state ?? Leave.LeaveStateEnum.Submitted;
            filterUser = filterUser?.ToLower() ?? "";
            sortOrder = sortOrder ?? "StartDate";
            page = page ?? 1;

            this.ViewBag.Holidays = GetCurrentHolidays(filterStartDate, filterEndDate);

            if (!typeof(Leave).HasProperty(sortOrder))
            {
                return this.RedirectToAction("OtherIndex");
            }

            orderDirection = orderDirection ?? ListSortDirection.Ascending;
            this.ViewData[sortOrder] = orderDirection ^ ListSortDirection.Descending;


            var loggedUserId = this.User.Identity.GetUserId();
            var leaves = await this.leaveService.GetLeavesOfAllSubordinatesAndSelfIncludingType(loggedUserId, (int) state.Value, filterUser,
                filterStartDate.Value, filterEndDate.Value, sortOrder, orderDirection.Value, page.Value);
            
            this.ViewBag.State = state;
            this.ViewBag.SortOrder = sortOrder;
            this.ViewBag.OrderDirection = orderDirection;
            this.ViewBag.FilterUser = filterUser;
            this.ViewBag.FilterStartDate = filterStartDate;
            this.ViewBag.FilterEndDate = filterEndDate;
            this.ViewBag.Page = page;
            this.ViewBag.RenderOptions = UserController.PagedListRenderOptions;

            return this.View(leaves);
        }

        [AuthorizeRedirect(Roles = "Administrator")]
        public async Task<ActionResult> AllLeaves()
        {
            var leaves = this.unitOfWork.LeaveRepository.GetAll(l => l.User, l => l.LeaveType);
            return this.View(await leaves);
        }

        [AuthorizeRedirect(Roles = "Administrator")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var leave = await this.unitOfWork.LeaveRepository.Get(id);
            if (leave == null)
            {
                return this.HttpNotFound();
            }

            this.ViewBag.Holidays = GetCurrentHolidays();
            var userList = await this.unitOfWork.UserRepository.GetAll();
            this.ViewBag.UserId = new SelectList(userList, "Id", "FullName", leave.UserId);
            return this.View(leave);
        }

        public async Task<ActionResult> Create(string id, bool forSelf = true)
        {
            this.ViewBag.Holidays = GetCurrentHolidays();

            if (id == null)
            {
                this.ViewBag.ForSelf = forSelf;
                if (!forSelf)
                {
                    var availableUsers = (await this.userService.GetAllSubordinatesAndSelf(this.User.Identity.GetUserId())).OrderBy(u => u.LastName).ToList();

                    this.ViewBag.UserSelectList = new SelectList(availableUsers, "Id", "FullName", this.User.Identity.GetUserId());
                }
                return this.View();
            }
            var leave = await this.unitOfWork.LeaveRepository.Get(id);
            if (leave == null || leave.UserId != this.User.Identity.GetUserId())
            {
                return this.HttpNotFound();
            }
            var model = new AddLeaveViewModel(leave);
            return this.View(model);
        }

        #endregion

        #region HttpPost

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateConfirmed(AddLeaveViewModel model)
        {
            model.DaysTaken = DateTools.HowManyDays(model.StartDate, model.EndDate);
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            Leave leave;
            string message;
            var isForSelf = model.UserId.IsNullOrWhiteSpace();
            if (!model.LeaveId.IsNullOrWhiteSpace())
            {
                leave = await this.unitOfWork.LeaveRepository.Get(model.LeaveId);
                leave.UpdateLeave(model);
                message = "Leave edited";
            }
            else
            {
                leave = new Leave(model, this.User.Identity.GetUserId());
                if (!isForSelf)
                {
                    leave.LeaveStateId = (int) Leave.LeaveStateEnum.Submitted;
                }
                this.unitOfWork.LeaveRepository.Add(leave);
                message = "Leave created";
            }

            var userId = this.User.Identity.GetUserId();
            var user = await this.unitOfWork.UserRepository.Get(userId);
            if (user.VacationDays < leave.DaysTaken)
            {
                this.ModelState.AddModelError("DaysTaken", Resources.Error.NotEnoughDays);
                return this.View(model);
            }
            await this.unitOfWork.Complete();
            this.TempData["SuccessMessage"] = message;
            this.TempData["NewId"] = leave.Id;
            return isForSelf ? this.RedirectToAction("Index") : this.RedirectToAction("OtherIndex");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRedirect(Roles = "Approver")]
        public async Task<ActionResult> Approve(string id)
        {
            var leave = await this.unitOfWork.LeaveRepository.Get(l => l.Id == id, includes: l => l.User);
            if (leave == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            leave.LeaveStateId = (int)Leave.LeaveStateEnum.Approved;
            if (leave.User != null)
            {
                if (leave.User.VacationDays < leave.DaysTaken)
                {
                    this.TempData["BadId"] = id;
                    this.TempData["ErrorMessage"] = Resources.Error.NotEnoughDaysForUser;
                    return this.RedirectToAction("OtherIndex");
                }
                leave.User.VacationDays -= leave.DaysTaken ?? 0;
                if (leave.DaysTaken == null)
                {
                    this.TempData["ErrorMessage"] = Resources.Error.BadDaysTaken;
                }
            }
            await this.unitOfWork.Complete();
//            if (leave.User != null)
//            {
//                var approverObj = await this.unitOfWork.UserRepository.Get(this.User.Identity.GetUserId());
//                var approver = approverObj.FullName;
//                var user = leave.User.FullName;
//                var startDate = leave.StartDate?.ToShortDateString();
//                var endDate = leave.EndDate?.ToShortDateString();
//                await this.emailService.SendNotification(leave.User.Email, approverObj.Email, string.Format(Resources.Email.LeaveApproved, user),
//                    string.Format(Resources.Email.LeaveApprovedMessage, user, startDate, endDate, approver));
//            }
            this.TempData["NewId"] = id;
            this.TempData["SuccessMessage"] = "Leave approved";
            return this.RedirectToAction("OtherIndex");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Submit(string id)
        {
            var leave = await this.unitOfWork.LeaveRepository.Get(id);
            if (leave == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            leave.LeaveStateId = (int)Leave.LeaveStateEnum.Submitted;
            await this.unitOfWork.Complete();
            this.TempData["NewId"] = id;
            this.TempData["SuccessMessage"] = "Leave submitted";

VacationsSystem/Views/Leave/OtherIndex.cshtml
@using Newtonsoft.Json
@using VacationsSystem.Extensions
@using VacationsSystem.Models
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common
@model IEnumerable<Leave>

@{
    ViewBag.Title = "Subordinates Leaves";
}

<h2 class="d-inline">@ViewBag.Title</h2>

@Html.ActionLink("Create new for someone", "Create", new { forSelf = false }, new { @class = "btn btn-primary text-white d-inline float-right" })

@using (Html.BeginForm("OtherIndex", "Leave", FormMethod.Get))
{
    <div class="form-group">
        <div class="col-md-12">
            @Html.TextBox("filterUser", "", htmlAttributes: new { placeholder = "Name", @class = "form-control d-inline align-middle m-1", style = "width: 150px" })
            @Html.TextBox("filterStartDate", null, format: "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control d-inline m-1 align-middle c-datepicker", style = "width: 150px" })
            @Html.TextBox("filterEndDate", null, format: "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control d-inline m-1 align-middle c-datepicker", style = "width: 150px" })
            <input type="submit" value="Filter" class="btn d-inline" />
        </div>
    </div>
}

<ul class="nav nav-tabs">
    <li class="nav-item">
        @{
            var hereState = Leave.LeaveStateEnum.Submitted;
            var active = ViewBag.State == hereState ? "active" : "";
            var name = EnumHelper<Leave.LeaveStateEnum>.GetDisplayValue(hereState);
        }

        @Html.ActionLink(Html.DisplayFor(model => name).ToString(), "OtherIndex",
            new
            {
                state = hereState,
                filterUser = ViewBag.FilterUser,
                filterStartDate = ((DateTime)ViewBag.FilterStartDate).UnifiedFormat(),
                filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
            }, new { @class = $"nav-link {active}" })
    </li>
    <li class="nav-item">
        @{
            hereState = Leave.LeaveStateEnum.Approved;
            active = ViewBag.State == hereState ? "active" : "";
            name = EnumHelper<Leave.LeaveStateEnum>.GetDisplayValue(hereState);
        }

        @Html.ActionLink(Html.DisplayFor(model => name).ToString(), "OtherIndex",
            new
            {
                state = hereState,
                filterUser = ViewBag.FilterUser,
                filterStartDate = ((DateTime)ViewBag.FilterStartDate).UnifiedFormat(),
                filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
            }, new { @class = $"nav-link {active}" })
    </li>
    <li class="nav-item">
        @{
            hereState = Leave.LeaveStateEnum.ApprovedAndNotified;
            active = ViewBag.State == hereState ? "active" : "";
            name = EnumHelper<Leave.LeaveStateEnum>.GetDisplayValue(hereState);
        }

        @Html.ActionLink(Html.DisplayFor(model => name).ToString(), "OtherIndex",
            new
            {
                state = hereState,
                filterUser = ViewBag.FilterUser,
                filterStartDate = ((DateTime)ViewBag.FilterStartDate).UnifiedFormat(),
                filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
            }, new { @class = $"nav-link {active}" })
    </li>
</ul>
@if (!Model.Any())
{
    <div class="jumbotron p-3 mt-3">
        @Html.Raw(Resources.Empty.ListEmptyFiltered)
    </div>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.User.FullName).ToString(), "OtherIndex",
                    new
                    {
                        sortOrder = "User.LastName",
                        orderDirection = ViewData["User.LastName"],
                        state = ViewBag.State,
                        filterUser = ViewBag.FilterUser,
                        filterStartDate = ((DateTime)ViewBag.FilterStartDate).UnifiedFormat(),
                        filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
                        page = ViewBag.Page
                    })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveType)
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.StartDate).ToString(), "OtherIndex",
                    new
                    {
                        sortOrder = "StartDate",
                        orderDirection = ViewData["StartDate"],
                        state = ViewBag.State,
                        filterUser = ViewBag.FilterUser,
                        filterStartDate = ((DateTime)ViewBag.FilterStartDate).UnifiedFormat(),
                        filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
                        page = ViewBag.Page
                    })
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.EndDate).ToString(), "OtherIndex",
                    new
                    {
                        sortOrder = "EndDate",
                        orderDirection = ViewData["EndDate"],
                        state = ViewBag.State,
                        filterUser = ViewBag.FilterUser,
                        filterStartDate = ((DateTime) ViewBag.FilterStartDate).UnifiedFormat(),
                        filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
                        page = ViewBag.Page
                    })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            @if (ViewContext.HttpContext.User.IsInRole("Approver") && (ViewBag.State & Leave.LeaveStateEnum.Submitted) != 0)
            {
                <th>
                    Actions
                </th>
            }
        </tr>

        @foreach (var item in Model)
        {
            var className = "";
            if (TempData["BadId"] != null && (string)TempData["BadId"] == item.Id)
            {
                className = "alert-danger highlight";
            }
            <tr class="@className">
                <td>
                    @Html.ActionLink(@Html.DisplayFor(modelItem => item.User.FullName).ToString(), "Details", "User", new { id = item.UserId }, null)
                </td>
                <td>
                    @(EnumHelper<Leave.LeaveTypeEnum>.GetDisplayValue(item.LeaveType))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                @if (ViewBag.State == Leave.LeaveStateEnum.Submitted)
                {
                    <td>
                        @if (ViewContext.HttpContext.User.IsInRole("Approver"))
                        {
                            <a href="#" data-toggle="modal" data-target="#confirmModal"
                               data-id="@Html.DisplayFor(modelItem => item.Id)"
                               data-name="@Html.DisplayFor(modelItem => item.User.FullName)"
                               data-from="@Html.DisplayFor(modelItem => item.StartDate)"
                               data-to="@Html.DisplayFor(modelItem => item.EndDate)"
                               data-type="@Html.DisplayFor(modelItem => item.LeaveType.Name)"
                               data-operation="Approve">Approve</a>
                            @Html.Raw(" | ")
                            <a href="#" data-toggle="modal" data-target="#confirmModal"
                               data-id="@Html.DisplayFor(modelItem => item.Id)"
                               data-name="@Html.DisplayFor(modelItem => item.User.FullName)"
                               data-from="@Html.DisplayFor(modelItem => item.StartDate)"
                               data-to="@Html.DisplayFor(modelItem => item.EndDate)"
                               data-type="@Html.DisplayFor(modelItem => item.LeaveType.Name)"
                               data-operation="Reject">Reject</a>
                        }
                    </td>
                }
            </tr>
        }

    </table>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("OtherIndex", new
{
    page,
    filterUser = ViewBag.FilterUser,
    filterStartDate = ((DateTime) ViewBag.FilterStartDate).UnifiedFormat(),
    filterEndDate = ((DateTime)ViewBag.FilterEndDate).UnifiedFormat(),
    state = ViewBag.State,
    sortOrder = ViewBag.SortOrder,
    orderDirection = ViewBag.OrderDirection
}), (PagedListRenderOptions)ViewBag.RenderOptions)
}

<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 id="modal-name"></h5>
                <strong class="d-inline card-title">Date: </strong><p class="d-inline">from </p><p class="d-inline" id="modal-from"></p><p class="d-inline"> to </p><p class="d-inline" id="modal-to"></p>
                <br />
                <strong class="d-inline">Type: </strong><p class="d-inline" id="modal-type"></p>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                <form id="modal-submit" action="" method="post">
                    @Html.AntiForgeryToken()
                    <input id="confirm-button" type="submit" value="Approve" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $('#confirmModal').on('show.bs.modal',
            function(event) {
                const button = $(event.relatedTarget);
                const id = button.data('id');
                const name = button.data('name');
                const from = button.data('from');
                const to = button.data('to');
                const type = button.data('type');
                const operation = button.data('operation');

                const endpoint = "@Url.Content("~/")";
                const url = `Leave/${operation}/`;
                const modal = $(this);
                modal.find('.modal-footer #modal-submit').attr('action', endpoint + url + id);
                modal.find('.modal-body #modal-name').text(name);
                modal.find('.modal-body #modal-from').text(from);
                modal.find('.modal-body #modal-to').text(to);
                modal.find('.modal-body #modal-type').text(type);
                modal.find('.modal-footer #confirm-button').val(operation);
                modal.find('.modal-header #modal-title').text(operation + ' leave');
            });
        var holidays = @Html.Raw(JsonConvert.SerializeObject(ViewBag.Holidays));
        $('.form-group').datepicker({
            format: 'yyyy-mm-dd',
            startDate: '-1y',
            endDate: '+1y',
            todayBtn: 'linked',
            todayHighlight: true,
            weekStart: 1,
            daysOfWeekHighlighted: "0,6",
            orientation: "bottom auto",
            inputs: $('.c-datepicker'),
            beforeShowDay: function(date) {
                const normDate = $.datepicker.formatDate('yy-mm-dd', date);
                if (holidays.indexOf(normDate) >= 0) {
                    return {
                        classes: 'holiday'
                    }
                }
// ReSharper disable once NotAllPathsReturnValue
            }
        });
    </script>
}