VacationsSystem/Controllers/UserRoleController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using VacationsSystem.Attributes;
using VacationsSystem.DAL.UnitOfWork;
using VacationsSystem.Models;

namespace VacationsSystem.Controllers
{
    [AuthorizeRedirect(Roles = "Administrator")]
    public class UserRoleController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public UserRoleController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        
        public async Task<ActionResult> Index()
        {
            return this.View(await this.unitOfWork.UserRoleRepository.GetAll());
        }
        
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userRole = await this.unitOfWork.UserRoleRepository.Get(id);
            if (userRole == null)
            {
                return this.HttpNotFound();
            }
            userRole.CustomUsers = await this.unitOfWork.UserRepository.Find(u => u.Roles.Any(r => r.RoleId == userRole.Id));
            return this.View(userRole);
        }
        
        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "Name", Exclude = "Id")] UserRole userRole)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(userRole);
            }
            this.unitOfWork.UserRoleRepository.Add(userRole);
            await this.unitOfWork.Complete();
            return this.RedirectToAction("Index");
        }
        
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userRole = this.unitOfWork.UserRoleRepository.Get(id);
            if (await userRole == null)
            {
                return this.HttpNotFound();
            }
            return this.View(await userRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] UserRole userRole)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(userRole);
            }
            this.unitOfWork.SetModified(userRole);
            await this.unitOfWork.Complete();
            return this.RedirectToAction("Index");
        }
        
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userRole = this.unitOfWork.UserRoleRepository.Get(id);
            if (await userRole == null)
            {
                return this.HttpNotFound();
            }
            return this.View(await userRole);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var userRole = this.unitOfWork.UserRoleRepository.Get(id);
            this.unitOfWork.UserRoleRepository.Remove(await userRole);
            await this.unitOfWork.Complete();
            return this.RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VacationsSystem/Views/Shared/_Layout.cshtml
@using VacationsSystem.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Marek Czaplicki" />
    <title>@ViewBag.Title - Leaves</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontsawesome")
    @Scripts.Render("~/javascript")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <div class="navbar-brand">
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Leave Application", "UserInfo", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Leave Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        if (ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item @Html.IsActive("Home", "Calendar")">@Html.ActionLink("Calendar", "Calendar", "Home", null, new { @class = "nav-link" })</li>
                            <li class="nav-item @Html.IsActive("Leave", "Index")">@Html.ActionLink("My Leaves", "Index", "Leave", null, new { @class = "nav-link" })</li>
                        }
                        if (ViewContext.HttpContext.User.IsInRole("Manager"))
                        {
                            <li class="nav-item @Html.IsActive("Leave", "OtherIndex")">@Html.ActionLink("Other Leaves", "OtherIndex", "Leave", null, new { @class = "nav-link" })</li>

                        }
                        if (ViewContext.HttpContext.User.IsInRole("Hr"))
                        {
                            <li class="nav-item @Html.IsActive("Hr", "LeaveList")">@Html.ActionLink("Leaves", "LeaveList", "Hr", null, new { @class = "nav-link" })</li>
                            <li class="nav-item @Html.IsActive("Hr", "UserList")">@Html.ActionLink("Employees", "UserList", "Hr", null, new { @class = "nav-link" })</li>
                        }
                        if (ViewContext.HttpContext.User.IsInRole("Administrator"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administrator Panel
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @Html.ActionLink("Users", "Index", "User", null, new { @class = $"dropdown-item {Html.IsActive("User", "Index")}" })
                                    @Html.ActionLink("User Roles", "Index", "UserRole", null, new { @class = $"dropdown-item {Html.IsActive("UserRole", "Index")}" })
                                    @Html.ActionLink("Leaves", "AllLeaves", "Leave", null, new { @class = $"dropdown-item {Html.IsActive("Leave", "AllLeaves")}" })
                                </div>
                            </li>
                        }
                        <li class="nav-item">@Html.ActionLink("Log out", "Logout", "Home", null, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li class="nav-item @Html.IsActive("Home", "Index")">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                        <li class="nav-item @Html.IsActive("Home", "Login")">@Html.ActionLink("Login", "Login", "Home", null, new { @class = "nav-link" })</li>
                        <li class="nav-item  @Html.IsActive("Home", "Register")">@Html.ActionLink("Register", "Register", "Home", null, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
            @if (Request.IsAuthenticated)
            {
                <span class="navbar-text small text-truncate mt-1">Logged in as @User.Identity.Name | 
                    <a href="#" data-theme="" class="theme-link">Toggle theme</a></span>
            }
            else
            {
                <a href="#" data-theme="" class="navbar-text small text-truncate mt-1 theme-link">Toggle theme</a>
            }
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="container body-content">
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-info alert-hide">@TempData["Message"]</div>
        }
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-hide">@TempData["SuccessMessage"]</div>
        }
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger alert-hide">@TempData["ErrorMessage"]</div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - UST Global Poland</p>
        </footer>
    </div>
    
    @RenderSection("scripts", required: false)
@*    <script language="javascript">*@
@**@
@*        var themes = {*@
@*            Light: '@Url.Content("~/Content/bootstrap.min.css")',*@
@*            Dark: '@Url.Content("~/Content/bootstrap_solar.min.css")'*@
@*        };*@
@*        var themeNames = {*@
@*            Light: 'Dark',*@
@*            Dark: 'Light'*@
@*        }*@
@*        var themesheet = $(`<link href="${themes['default']}" rel="stylesheet" />`);*@
@*        themesheet.appendTo('head');*@
@**@
@*        function supports_html5_storage() {*@
@*            try {*@
@*                return 'localStorage' in window && window['localStorage'] !== null;*@
@*            } catch (e) {*@
@*                return false;*@
@*            }*@
@*        }*@
@**@
@*        function set_theme(theme, themeName) {*@
@*            themesheet.attr('href', theme);*@
@*            $('.theme-link').attr('data-theme', themes[themeName]).text(themeName);*@
@**@
@*            if (supports_storage) {*@
@*                localStorage.theme = theme;*@
@*                localStorage.themeName = themeName;*@
@*            }*@
@*        }*@
@**@
@*        var supports_storage = supports_html5_storage();*@
@**@
@*        /* On load, set theme from local storage */*@
@*        if (supports_storage) {*@
@*            var theme = localStorage.theme;*@
@*            var themeName = localStorage.themeName;*@
@*            if (theme) {*@
@*                set_theme(theme, themeName);*@
@*            } else {*@
@*                set_theme(themes['Light'], themeNames['Light']);*@
@*            }*@
@*        } else {*@
@*            /* Don't annoy user with options that don't persist */*@
@*            $('.theme-link').hide();*@
@*        }*@
@*        $('.theme-link').click(function () {*@
@*            const themeurl = $(this).attr('data-theme');*@
@*            set_theme(themeurl, themeNames[$(this).text()]);*@
@*        });*@
@*    </script>*@

</body>
</html>